flathub/com.fightcade.Fightcade

com.fightcade.Fightcade.yml
scripts/fightcade-launcher.sh

This should fix a problem with game-specific input mappings not
persisting between sessions.
Resolves https://github.com/flathub/com.fightcade.Fightcade/issues/4

symlink entire emulator config dir

---

com.fightcade.Fightcade.yml
fightcade-flatpak-romsdir.patch
metainfo.xml
scripts/fightcade-launcher.sh

Small improvements to Flatpak integration
* Patches the Electron frontend to fix 'Open ROMs Dir' (Note: due to an upstream bug this doesn't work on xdg-desktop 1.8.0~1.8.2)
* Fix FBNeo configs not persisting between emulator sessions

Stable release 2.0.82-1

---

scripts/fightcade-launcher.sh

Alert the user that the wine prefix may take some time to be created on
first boot or updated on subsequent boots.
On slower systems this can take a decent amount of time (upwards of 2
minutes tested on a 2-core Fedora Silverblue VM) and without any output
will appear to just be hanging.

fightcade-launcher: alert the user about wine prefix

---

com.fightcade.Fightcade.yml
scripts/fightcade-launcher.sh

Implement a workaround for Valid.Ext not existing as well as add a
symlink for the Snes9x configuration file.

Initial Snes9x support

---

scripts/fightcade-launcher.sh

Put an 'N' into Valid.Ext to stop Snes9x from crashing
For some reason Snes9x requires the Valid.Ext file to not be empty to
not crash, putting an 'N' in it gets past the initial crash and allows
the emulator to load.

snes9x: fix early crash

---

com.fightcade.Fightcade.yml

Flycast was changed to a native client in Fightcade v2.1.1, which
adds the additional dependency of libzip.

flycast: add libzip 1.7.3 dependency

---

com.fightcade.Fightcade.yml

At some point when switching to WoW64 some of the cleanup was dropped
from the wine build. This commit re-adds this dropped cleanup.

wine: re-add dropped cleanup

---

com.fightcade.Fightcade.yml

These are needed to submit com.fightcade.Fightcade.Wine to Flathub to
get Wine into a separate Flatpak.

Add wine extension points to com.fightcade.Fightcade

---

com.fightcade.Fightcade.yml
scripts/wine.sh

Since wine is planning to be shipped in an extension soon we should throw a graphical error to let users know they are missing an extension when they attempt to run Windows emulators.
Because Fightcade runs Wine from `Resources/wine.sh` we should overload this to do a check on `/app/wine/bin/wine` to see if it exists.
This should have no effect on native games.

wine.sh: raise a zenity error window when wine can't be found

---

com.fightcade.Fightcade.yml
scripts/fightcade-launcher.sh
scripts/wine.sh

Using ~/.wine as our wine prefix causes a conflict when uses override
with --filesystem=home which can result in wine not running if said wine
prefix is from a newer release of wine.
Move the wine prefix into /var/data to avoid clashing with anything from
the host OS when overriding.

Change wineprefix to /var/data/winepfx

---

com.fightcade.Fightcade.yml

This adds the rest of the fc2 jsons to the symlink build commands so the remaining platforms are supported. Otherwise: 
(Yeah, I'm a Fightcade weirdo.)

fix: add remaining fc2 json files

---

flathub.json

According to https://github.com/flathub/flatpak-builder-lint/issues/28 the modified publish delay option in Flathub.json is deprecated and no longer meant be used.

flathub.json: remove publish delay

---

com.fightcade.Fightcade.yml

Attempting to resolve https://github.com/flathub/com.fightcade.Fightcade/issues/91#issuecomment-1359962133
It seems the Ubuntu 22 dependencies for Flycast were snuck into today's Fightcade update without warning, thus breaking compatibility with Flatpak's 21.08 runtimes. Last time I worked with blueminder to try to make the new Flycast run in the Flatpak some 22.08 runtimes were unavailable, hopefully they're ready to go now.

22.08 runtime update

---

com.fightcade.Fightcade.yml
scripts/fightcade-launcher.sh

Fightcade has changed how the fbneo-training-mode directory is laid out which breaks our older, more complex workaround. Switch to using a simpler symlink-based workaround.
Related to #95

Update FBNeo training mode workaround

---

scripts/fightcade-launcher.sh
scripts/wine.sh

The old Wine 5 prefix seems to be invalid when upgraded to Wine 8, creating a new prefix at /var/data/winepfx-8 allows wine to launch normally.

wine: move to new prefix for wine 8

---

metainfo.xml

There's been enough major changes (including a Wine bump) to warrant a minor version upgrade of the Flatpak.

Release version 2.3 of Fightcade Flatpak

---

com.fightcade.Fightcade.yml
flathub.json
metainfo.xml

Removed Flathub bot automerge since it's no longer allowed: https://docs.flathub.org/docs/for-app-authors/linter/#flathub-json-automerge-enabled

flathub.json: remove flathubbot automerge

---

flathub.json

We were granted an exception in
https://github.com/flathub-infra/flatpak-builder-lint/pull/411 since the Fightcade client is functionally useless if it's out of date.
Re-enable the option to allow Flathubbot to automatically merge PRs when new Fightcade clients are published.

flathub.json: re-enable flathubbot automerge

---

com.fightcade.Fightcade.yml

Required since the last update. Was meant to be set by Fightcade but was not included in the current release, so let's set it ourselves.

Add FLYCAST_ROOT environment variable

---

.gitignore
com.fightcade.Fightcade.yml
metainfo.xml

Flycast is now distributed as an AppImage by default in Fightcade. Install unappimage and use that to extract the flycast-dojo binary out of the AppImage.

flycast: extract binary from AppImage

---

com.fightcade.Fightcade.yml
scripts/steamdeck-xdgopen.sh

Add a workaround to get Fightcade working properly in Steam Deck gaming mode.
Gaming mode does provide `xdg-open`, but for some reason it doesn't seem to work properly for URIs provided by Flatpaks. This commit adds a script that intercepts the `xdg-open` command and forwards any `fcade://` commands directly to `fcade-quark`.
Fixes #147

Add a workaround for Steam Deck Gaming mode compat

---

scripts/fightcade-launcher.sh

For some reason ReCaptcha needs Zypak to be run with --no-sandbox.
Fixes #123

zypak: fix ReCaptcha

---

com.fightcade.Fightcade.yml

libao seems to have an issue on GCC9[0], so pass
-Wno-error=implicit-function-declaration to the compiler to downgrade the error to a warning (according to GCC docs[1].)
This error was present as a warning on previous runtimes, but it's since been upgraded to a compilation error.
[0] https://gitlab.xiph.org/xiph/libao/-/issues/2318
[1] https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

manifest: update all runtimes to 24.08

---

com.fightcade.Fightcade.yml
scripts/fightcade-launcher.sh
scripts/get-wine-prefix.sh
scripts/wine.sh

Remove use of the com.fightcade.Fightcade.Wine extension and switch to using org.winehq.Wine as our baseapp.
This means we have to build Zypak ourselves, but that's much simpler than maintaining an entire Wine build.
This commit also does a little bit of fixing to how we clear stale wineprefixes.

Switch to org.winehq.Wine
